#!/usr/bin/python3
# test_cycles.py
from graph import Graph
g = Graph(4)
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(1, 2)
g.add_edge(2, 0)
g.add_edge(2, 3)
g.add_edge(3, 3)
print("Graph 1 (Has Cycles)")
print("Has Cycles?:")
print(g.is_cyclic())
print("Cycle Sequences?:")
print(g.cycle_list())
g2 = Graph(4)
g2.add_edge(0, 1)
g2.add_edge(1, 2)
g2.add_edge(3, 2)
print("Graph 2 (No Cycles)")
print("Has Cycles?:")
print(g2.is_cyclic())
print("Cycle Sequences?:")
print(g2.cycle_list())
